# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish release to PyPi

on:
  release:
    types: [published]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Check versions match
      run: |
        PUBLISHING_VERSION=${{ github.event.release.tag_name }}
        grep -qE '__version__ = "'$PUBLISHING_VERSION'"' nibe/__init__.py
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1.12
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
